### ISSUE TITLE
[ERROR] Invalid URI format

### ISSUE THREAD

**Issue by kazeyfr** [ZyXProFR/vinted-scraper#1]
Hey, i just copy-pasted the exemple of the vinted-scraper but i got this error: Invalid URI format

here is the url i used: https://vinted.fr/vetements?search_text=pantalon

![Code_svHV7C4e7s](https://user-images.githubusercontent.com/63236045/188289602-e8cb94b4-de05-44fb-b5c9-c547b92013d5.png)

**Comment by ZyXProFR** [comment]
You must use **www** subdomain like this : `https://www.vinted.fr/vetements?search_text=pantalon`.

Tell me if this fixes the problem.

**Comment by ZyXProFR** [comment]
I added a condition in version **1.2.3** to make the **www** optional. By downloading this update you should be able to use Vinted links without the **www** subdomain
